In [3]:
%matplotlib inline
import matplotlib.pyplot as plt
import numpy as np

print("Hello World!")

Hello World!


In [ ]:
x = np.array([1, 2])
y = np.array([-2, 1])
a = np.dot(x, y)
print("\n",a)

b = np.linalg.norm(x) #Euclidean norm
c = np.sqrt(x[0]**2 + x[1]**2)
print("\n", b, c)

theta = np.arccos(np.dot(x,y) / (np.linalg.norm(x) * np.linalg.norm(y)))

B = np.array([[3,2,1], [2,6,5], [1,5,9]], dtype=float)
print("\n", B)
print("\n", B- B.T)

z = np.random.rand(3)
v = B @ z
print("\n", v.shape)

print("\n", z.T @ B @ z)

print("\n", np.trace(B))
print("\n", np.linalg.det(B))

D, U = np.linalg.eig(B)
print("\n", D)
print("\n", U)

print("\n", np.dot(U[:,0], U[:,1]))
print("\n", U @ U.T)


 0

 2.23606797749979 2.23606797749979

 [[3. 2. 1.]
 [2. 6. 5.]
 [1. 5. 9.]]

 [[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]

 (3,)

 12.919667419025771

 18.0

 65.00000000000004

 [13.11766327  3.44324229  1.43909444]

 [[-0.19527095 -0.74608451  0.63657455]
 [-0.59990492 -0.42261825 -0.67934373]
 [-0.77587586  0.5145403   0.3650547 ]]

 -2.8150224912813863e-16

 [[ 1.00000000e+00 -5.55111512e-17  8.32667268e-17]
 [-5.55111512e-17  1.00000000e+00  5.55111512e-17]
 [ 8.32667268e-17  5.55111512e-17  1.00000000e+00]]
